-- Amazon
-- Creating database
create database amazon;

-- Using database
use amazon;

-- Creating tables

-- Category table
create table category(
category_id int primary key,
category_name varchar(30)
);
select * from category;
describe category;

-- Customer table
create table customer(
customer_id int primary key,
first_name varchar(20),
last_name varchar(20),
state varchar(20)
);
select * from customer;
describe customer;

-- Seller table
create table seller(
seller_id int primary key,
seller_name varchar(20),
origin varchar(20)
);
select * from seller;
describe seller;

-- product table
-- I have directly imported the product table
describe product;
-- Now let's add primary key
alter table product 
add constraint pk_product primary key (product_id);
-- Now let's add foreign key
alter table product 
add constraint fk_product foreign key (category_id) references category(category_id);
-- Added
select * from product;

-- inventory 
describe inventory;
-- the inventory id column name needs to be changed
alter table inventory
rename column ï»¿inventory_id to inventory_id;
-- Let's add primary key
alter table inventory
add primary key (inventory_id);
-- Let's add foreign key  
alter table inventory
add constraint fk_product_id foreign key (product_id) references product(product_id);
-- Added
select * from inventory;

-- orders
create table orders(
order_id int primary key,
order_date date,
customer_id int,
seller_id int,
order_status varchar(20),
foreign key (customer_id) references customer(customer_id),
foreign key (seller_id) references seller(seller_id)
);
select * from orders;

-- payment
create table payment(
payment_id int primary key,
order_id int,
payment_date date,	
payment_status varchar(20),
foreign key (order_id) references orders(order_id)
);
select * from payment;

-- shipping
-- I have directly imported the csv file without creating table
-- Let's do few modifications
-- Checking the data types, column names and null values
describe shipping ;
select * from shipping;
-- Adding primary key
alter table shipping
add primary key (shipping_id);
-- changing column data type
alter table shipping
modify shipping_date date;
-- handling blank values and converting into NULL
update shipping
set return_date = NULL
where return_date = '';
-- Changing column data type
alter table shipping
modify return_date date;
-- Changing column name
alter table shipping
rename column `shipping providers` to shipping_providers;
-- Adding foreign key
alter table shipping
add foreign key (order_id) references orders(order_id);

-- order_items
-- I have directly imported the csv file without creating table
describe order_item;
-- Let's do few modifications
-- Checking the data types, column names and null values
-- Changing column name
alter table order_item
rename column ï»¿order_item_id to order_item_id;
-- Adding primary key
alter table order_item
add constraint pk_order_item primary key (order_item_id);
-- Adding foreign key 1
alter table order_item
add constraint fk1_product foreign key (product_id) references product(product_id);
-- Adding foreign key 2
alter table order_item
add constraint fk2_orders foreign key (order_id) references orders(order_id);
-- Added
select * from order_item;

-- DATA IMPORTED --

-- Exploratory data analysis (EDA)
select * from category;
select * from customer;
select * from inventory;
select * from order_item;
select * from orders;
select * from payment;
select * from product;
select * from seller;
select * from shipping;

-- Since the return_date column in shipping table has large number of null values
-- So let's check the products that have been Returned
select * from shipping
where  return_date is not null ;

-- Adding a total_sales column which will help in the upcoming problems
Alter table order_item
Add column total_sales Float;

-- updating total_sales column as qty * price per unit 
update order_item
set total_sales = quantity * price_per_unit;
select * from order_item;

-- Problem Solving
-- QUESTION 1
-- QUERY THE TOP 10 PRODUCTS BY TOTAL SALES VALUE INCLUDING PRODUCT NAME, TOTAL QUANTITY SOLD, TOTAL SALES VALUE
  WITH TOP_PRODUCTS AS(
  		SELECT p.product_name as PRODUCT_NAME,
        sum(oi.quantity) as TOTAL_QUANTITY_SOLD,
        round(sum(oi.total_sale))  as TOTAL_SALE_VALUE
        from products p
        join order_items oi on oi.product_id=p.product_id
        join orders o on oi.order_id=o.order_id
        WHERE o.order_status <> 'Returned'
        GROUP BY  p.product_name,p.product_id
        )
select * from top_products
order by TOTAL_SALE_VALUE desc
limit 10;

-- question 2
-- CALCULATE TOTAL REVENUE GENERATED BY EACH PRODUCT CATEGORY AND INCLUDE THE PERCENTAGE CONTRIBUTION OF EACH CATEGORY TO TOTAL REVENUE
WITH revenue AS (
SELECT
c.category_name,
round(SUM(oi.total_sale),2) AS total_revenue,
round(
(sum(oi.total_sale)/
(select sum(total_sale) from order_items oi ))
*100,2) as revenue_percentage
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN category c ON p.category_id = c.category_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY c.category_name
)
select * 
from revenue;


-- question 3
-- COMPUTE THE AVERAGE ORDER VALUE FOR EACH CUSTOMER AND INCLUDE ONLY CUSTOMERS WITH MORE THAN 5 ORDER
SELECT
    c.customer_id,
    ROUND(SUM(oi.total_sale) / COUNT(DISTINCT o.order_id), 2) AS AOV,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id
HAVING COUNT(DISTINCT o.order_id) > 5;

SELECT
    c.customer_id,
    ROUND(SUM(oi.total_sale) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id
HAVING COUNT(DISTINCT o.order_id) > 5;

-- question 4
--	 query monthly total sales over the past year and display the current month's sales along with the previous month's sales.
with monthly_sale as(
select 
month (o.order_date) as month,
year (o.order_date) as year,
round(sum(oi.total_sale),2) as total_sale
FROM order_items oi
join orders o on o.order_id=oi.order_id
WHERE o.order_status = 'Completed'
and DATE_SUB(CURDATE(), INTERVAL 1 YEAR)
group by  1,2
order by year, month 
)
select month, year, total_sale as current_month_sale,
lag(total_sale) over(order by year,month ) as previous_month_sale
from monthly_sale;

-- QUESTION 5
-- FIND CUSTOMER WHO HAVE REGISTERED BUT NEVER PLACED AN ORDER, LISTING CUSTOMER DETAILS AND THE TIME SINCE THEIR REGISTRATION. 

select *
from customers 
where customer_id not in (select distinct customer_id from orders);

-- QUESTION 6
-- IDENTIFY THE LEAST SELLING PRODUCT CATEGORY FOR EACH STATE AND INCLUDE THE TOTAL SALES FOR THAT CATEGORY withIN EACH STATE
with least_selling as (
SELECT c.state as state,
 ca.category_name as category,
round(sum(oi.total_sale),2) total_sale,
dense_rank() over (partition by ca.category_name order by sum(oi.total_sale) ) as least_selling_category 
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p ON oi.product_id = p.product_id
JOIN category cA ON p.category_id = ca.category_id
WHERE o.order_status = 'Completed'
group by 1,2
)
select state, category, total_sale 
from least_selling
where least_selling_category=1
;

-- 7. Calculate the customer lifetime value (CLTV) for each customer and rank customers based on their CLTV.
with CLTV as (
  select c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) as customer_name, -- joining first & last name as full customer_name
    SUM(oi.total_sales) as lifetime_value
  from customer c
  join orders o on c.customer_id = o.customer_id
  join order_item oi on o.order_id = oi.order_id
  group by c.customer_id, customer_name
)
select 
  customer_id,
  customer_name,
  lifetime_value,
  rank() over (order by lifetime_value desc) as ranked
from CLTV;

-- 8. Query products with stock levels below a certain threshold (e.g., less than 10 units) and include the last restock date and warehouse information.
select 
	i.inventory_id,
	p.product_name,
	i.stock as current_stock_left,
	i.last_stock_date,
	i.warehouse_id
from inventory i
join product p
on p.product_id = i.product_id
where stock < 10 ;

-- 9. Calculate the percentage of successful payments across all orders and include a breakdown by payment status such as failed and pending.
select 
	p.payment_status,
	COUNT(*) as total_cnt,
	COUNT(*) * 100.0 / (select COUNT(*) from payment) as Percentage
from orders o
join payment p
on o.order_id = p.order_id
group by 1;

-- 10. Query the top 10 products by the number of returns and display the return rate as a percentage of total units sold for each product.
select 
    p.product_id,
    p.product_name,
    COUNT(*) as total_units_sold,
    SUM(case when o.order_status = 'Returned' then 1 else 0 end) AS total_returned,
    CAST(SUM(CASE WHEN o.order_status = 'Returned' then 1 else 0 end) as decimal(10,2)) 
        / CAST(COUNT(*) as decimal(10,2)) * 100 as return_percentage
from order_item oi
join product p 
    on oi.product_id = p.product_id
join orders o 
    on o.order_id = oi.order_id
group by 
    p.product_id, 
    p.product_name
order by 
    total_returned desc
limit 10;
