-- Amazon
-- Creating database
create database amazon_project;

-- Using database
use amazon_project;

CREATE DATABASE AMAZON_PROJECT;
USE AMAZON_PROJECT;


-- customer
select * from customers;

-- rename column name
ALTER TABLE customers
RENAME COLUMN Customer_id TO customer_id;

-- check duplicate values
SELECT customer_id, COUNT(*)
FROM customers
GROUP BY customer_id
HAVING COUNT(*) > 1;

-- ASSIGN PRIMARY KEY
ALTER TABLE customers
add constraint pk_customers
primary key (Customer_id);

-- CATEGORY TABLE
SELECT * FROM CATEGORY;

-- RENAME COLUMN
ALTER TABLE category
RENAME COLUMN Category_id TO category_id;

-- ASSIGN KEY
ALTER TABLE category
add constraint pk_category
primary key (Category_id);

-- 
SET SQL_SAFE_UPDATES = 0;
UPDATE category
SET category_name =  CONCAT(
        UPPER(SUBSTRING(category_name, 1, 1)),
        LOWER(SUBSTRING(category_name, 2))
    );
SET SQL_SAFE_UPDATES = 1;

-- SELLERS TABLE
SELECT * FROM SELLERS;

-- RENAME SELLERS
ALTER TABLE SELLERS
RENAME COLUMN ï»¿seller_id TO seller_id;

-- ASSIGN KEY
ALTER TABLE sellers
add constraint pk_sellers
primary key (seller_id);

-- PRODUCTS TABLE
SELECT * FROM products;

-- ASSIGN PRIMARY KEY AND FOREIGN KEY
ALTER TABLE products
ADD CONSTRAINT pk_products
primary key (product_id);

ALTER TABLE products
ADD CONSTRAINT fk_products_category
FOREIGN KEY (category_id) REFERENCES category(category_id);

-- ORDERS
SELECT * FROM orders;

-- RENAME COLUMN
ALTER TABLE orders
RENAME COLUMN ï»¿order_id to order_id;

-- ASSIGN PRIMARY KEY AND FOREIGN KEY
ALTER TABLE orders
ADD CONSTRAINT pk_orders
PRIMARY KEY (order_id);

ALTER TABLE orders
ADD CONSTRAINT fk_orders_customer
FOREIGN KEY(customer_id) REFERENCES customers(customer_id);

-- ORDER_ITEMS
SELECT * FROM order_items;

-- RENAME COLUMNS
ALTER TABLE order_items
RENAME COLUMN ï»¿order_item_id to order_item_id;

-- ASSIGN PRIMARY KEY 
ALTER TABLE order_items
ADD CONSTRAINT pk_order_items
PRIMARY KEY (order_item_id);

-- ASSIGN FOREIGN KEY
ALTER TABLE order_items
ADD CONSTRAINT fk_order_item
FOREIGN KEY (order_id) REFERENCES orders(order_id);

ALTER TABLE order_items
ADD CONSTRAINT fk_order_item_product
FOREIGN KEY (product_id) REFERENCES products(product_id);

-- ADD NEW COLUMN
ALTER table order_items
ADD column total_sale float;
SET SQL_SAFE_UPDATES = 0;
UPDATE order_items
SET total_sale= quantity * price_per_unit;
SET SQL_SAFE_UPDATES = 1;
-- PAYMENTS TABLE
SELECT * FROM payments;

-- RENAME COLUMN
ALTER TABLE PAYMENTS
RENAME COLUMN ï»¿payment_id to payment_id;

-- ASSIGN KEY 
ALTER TABLE payments
ADD CONSTRAINT PK_PAYMENT_ID
PRIMARY KEY (payment_id);

-- ASSIGN FOREIGN KEY
ALTER TABLE payments
ADD CONSTRAINT FK_PAYMENTS_ORDER
FOREIGN KEY (order_id) REFERENCES orders(order_id);

-- SHIPPING TABLE
SELECT * FROM SHIPPING;
-- RENAME COLUMN
ALTER TABLE SHIPPING
RENAME COLUMN ï»¿shipping_id TO shipping_id;

-- ASSIGN PRIMARY KEY AND FOREIGN KEY
ALTER table shipping
ADD CONSTRAINT pk_shipping
PRIMARY KEY (shipping_id);

ALTER table shipping
ADD CONSTRAINT fk_shipping_order
FOREIGN KEY (order_id) REFERENCES orders(order_id);

-- inventory table
select * from inventory;

-- RENAME COLUMN
ALTER TABLE inventory
RENAME COLUMN ï»¿inventory_id TO inventory_id;

-- ASSIGN PRIMARY KEY
ALTER TABLE inventory
add constraint pk_inventory
primary key (inventory_id);

-- ASSIGN FOREIGN KEY
ALTER TABLE inventory
ADD CONSTRAINT fk_inventory_product
foreign key(product_id) references products(product_id);

-- DATA IMPORTED --

-- Exploratory data analysis (EDA)
select * from category;
select * from customer;
select * from inventory;
select * from order_item;
select * from orders;
select * from payment;
select * from product;
select * from seller;
select * from shipping;

-- Since the return_date column in shipping table has large number of null values
-- So let's check the products that have been Returned
select * from shipping
where  return_date is not null ;

-- Adding a total_sales column which will help in the upcoming problems
Alter table order_item
Add column total_sales Float;

-- updating total_sales column as qty * price per unit 
update order_item
set total_sales = quantity * price_per_unit;
select * from order_item;

-- Problem Solving
-- QUESTION 1
-- QUERY THE TOP 10 PRODUCTS BY TOTAL SALES VALUE INCLUDING PRODUCT NAME, TOTAL QUANTITY SOLD, TOTAL SALES VALUE
  WITH TOP_PRODUCTS AS(
  		SELECT p.product_name as PRODUCT_NAME,
        sum(oi.quantity) as TOTAL_QUANTITY_SOLD,
        round(sum(oi.total_sale))  as TOTAL_SALE_VALUE
        from products p
        join order_items oi on oi.product_id=p.product_id
        join orders o on oi.order_id=o.order_id
        WHERE o.order_status <> 'Returned'
        GROUP BY  p.product_name,p.product_id
        )
select * from top_products
order by TOTAL_SALE_VALUE desc
limit 10;

-- question 2
-- CALCULATE TOTAL REVENUE GENERATED BY EACH PRODUCT CATEGORY AND INCLUDE THE PERCENTAGE CONTRIBUTION OF EACH CATEGORY TO TOTAL REVENUE
WITH revenue AS (
SELECT
c.category_name,
round(SUM(oi.total_sale),2) AS total_revenue,
round(
(sum(oi.total_sale)/
(select sum(total_sale) from order_items oi ))
*100,2) as revenue_percentage
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN category c ON p.category_id = c.category_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY c.category_name
)
select * 
from revenue;


-- question 3
-- COMPUTE THE AVERAGE ORDER VALUE FOR EACH CUSTOMER AND INCLUDE ONLY CUSTOMERS WITH MORE THAN 5 ORDER
SELECT
    c.customer_id,
    ROUND(SUM(oi.total_sale) / COUNT(DISTINCT o.order_id), 2) AS AOV,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id
HAVING COUNT(DISTINCT o.order_id) > 5;

SELECT
    c.customer_id,
    ROUND(SUM(oi.total_sale) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id
HAVING COUNT(DISTINCT o.order_id) > 5;

-- question 4
--	 query monthly total sales over the past year and display the current month's sales along with the previous month's sales.
with monthly_sale as(
select 
month (o.order_date) as month,
year (o.order_date) as year,
round(sum(oi.total_sale),2) as total_sale
FROM order_items oi
join orders o on o.order_id=oi.order_id
WHERE o.order_status = 'Completed'
and DATE_SUB(CURDATE(), INTERVAL 1 YEAR)
group by  1,2
order by year, month 
)
select month, year, total_sale as current_month_sale,
lag(total_sale) over(order by year,month ) as previous_month_sale
from monthly_sale;

-- QUESTION 5
-- FIND CUSTOMER WHO HAVE REGISTERED BUT NEVER PLACED AN ORDER, LISTING CUSTOMER DETAILS AND THE TIME SINCE THEIR REGISTRATION. 

select *
from customers 
where customer_id not in (select distinct customer_id from orders);

-- QUESTION 6
-- IDENTIFY THE LEAST SELLING PRODUCT CATEGORY FOR EACH STATE AND INCLUDE THE TOTAL SALES FOR THAT CATEGORY withIN EACH STATE
with least_selling as (
SELECT c.state as state,
 ca.category_name as category,
round(sum(oi.total_sale),2) total_sale,
dense_rank() over (partition by ca.category_name order by sum(oi.total_sale) ) as least_selling_category 
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p ON oi.product_id = p.product_id
JOIN category cA ON p.category_id = ca.category_id
WHERE o.order_status = 'Completed'
group by 1,2
)
select state, category, total_sale 
from least_selling
where least_selling_category=1
;

-- 7. Calculate the customer lifetime value (CLTV) for each customer and rank customers based on their CLTV.
with CLTV as (
  select c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) as customer_name, -- joining first & last name as full customer_name
    SUM(oi.total_sales) as lifetime_value
  from customer c
  join orders o on c.customer_id = o.customer_id
  join order_item oi on o.order_id = oi.order_id
  group by c.customer_id, customer_name
)
select 
  customer_id,
  customer_name,
  lifetime_value,
  rank() over (order by lifetime_value desc) as ranked
from CLTV;

-- 8. Query products with stock levels below a certain threshold (e.g., less than 10 units) and include the last restock date and warehouse information.
select 
	i.inventory_id,
	p.product_name,
	i.stock as current_stock_left,
	i.last_stock_date,
	i.warehouse_id
from inventory i
join product p
on p.product_id = i.product_id
where stock < 10 ;

-- 9. Calculate the percentage of successful payments across all orders and include a breakdown by payment status such as failed and pending.
select 
	p.payment_status,
	COUNT(*) as total_cnt,
	COUNT(*) * 100.0 / (select COUNT(*) from payment) as Percentage
from orders o
join payment p
on o.order_id = p.order_id
group by 1;

-- 10. Query the top 10 products by the number of returns and display the return rate as a percentage of total units sold for each product.
select 
    p.product_id,
    p.product_name,
    COUNT(*) as total_units_sold,
    SUM(case when o.order_status = 'Returned' then 1 else 0 end) AS total_returned,
    CAST(SUM(CASE WHEN o.order_status = 'Returned' then 1 else 0 end) as decimal(10,2)) 
        / CAST(COUNT(*) as decimal(10,2)) * 100 as return_percentage
from order_item oi
join product p 
    on oi.product_id = p.product_id
join orders o 
    on o.order_id = oi.order_id
group by 
    p.product_id, 
    p.product_name
order by 
    total_returned desc
limit 10;
-- EXTRA
-- Identified the highest-demand product in each state based on total quantity sold, enabling better understanding of customer preferences.
WITH product_demand AS (
SELECT c.state, p.product_name,
SUM(oi.quantity) AS total_quantity,
DENSE_RANK() OVER ( PARTITION BY c.state ORDER BY SUM(oi.quantity)  DESC ) AS rnk
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p ON oi.product_id = p.product_id
WHERE o.order_status = 'Completed'
GROUP BY c.state, p.product_name
)
SELECT state, product_name AS highest_demand_product,
total_quantity
FROM product_demand
WHERE rnk = 1
ORDER BY state;
